// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: clusters.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const getCluster = `-- name: GetCluster :one
SELECT id, tenant_id, cloud_provider, region, last_heartbeat, status, agent_version, deregistered_at, created_at FROM workload_clusters WHERE id = $1
`

func (q *Queries) GetCluster(ctx context.Context, id uuid.UUID) (WorkloadCluster, error) {
	row := q.db.QueryRowContext(ctx, getCluster, id)
	var i WorkloadCluster
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CloudProvider,
		&i.Region,
		&i.LastHeartbeat,
		&i.Status,
		&i.AgentVersion,
		&i.DeregisteredAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertCluster = `-- name: InsertCluster :one
INSERT INTO workload_clusters (id, tenant_id, cloud_provider, region)
VALUES ($1, $2, $3, $4)
RETURNING id, tenant_id, cloud_provider, region, last_heartbeat, status, agent_version, deregistered_at, created_at
`

func (q *Queries) InsertCluster(ctx context.Context, iD uuid.UUID, tenantID uuid.UUID, cloudProvider string, region string) (WorkloadCluster, error) {
	row := q.db.QueryRowContext(ctx, insertCluster,
		iD,
		tenantID,
		cloudProvider,
		region,
	)
	var i WorkloadCluster
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CloudProvider,
		&i.Region,
		&i.LastHeartbeat,
		&i.Status,
		&i.AgentVersion,
		&i.DeregisteredAt,
		&i.CreatedAt,
	)
	return i, err
}

const listClustersByTenant = `-- name: ListClustersByTenant :many
SELECT id, tenant_id, cloud_provider, region, last_heartbeat, status, agent_version, deregistered_at, created_at FROM workload_clusters
WHERE tenant_id = $1 AND deregistered_at IS NULL
ORDER BY created_at
`

func (q *Queries) ListClustersByTenant(ctx context.Context, tenantID uuid.UUID) ([]WorkloadCluster, error) {
	rows, err := q.db.QueryContext(ctx, listClustersByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkloadCluster
	for rows.Next() {
		var i WorkloadCluster
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.CloudProvider,
			&i.Region,
			&i.LastHeartbeat,
			&i.Status,
			&i.AgentVersion,
			&i.DeregisteredAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateClusterHeartbeat = `-- name: UpdateClusterHeartbeat :exec
UPDATE workload_clusters
SET last_heartbeat = NOW(), status = 'healthy'
WHERE id = $1
`

func (q *Queries) UpdateClusterHeartbeat(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, updateClusterHeartbeat, id)
	return err
}
