// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type BasePlan struct {
	ID           uuid.UUID `db:"id" json:"id"`
	ResourceType string    `db:"resource_type" json:"resource_type"`
	Name         string    `db:"name" json:"name"`
	CreditAmount int64     `db:"credit_amount" json:"credit_amount"`
}

type CreditAdjustment struct {
	ID           uuid.UUID      `db:"id" json:"id"`
	TenantID     uuid.UUID      `db:"tenant_id" json:"tenant_id"`
	ResourceType string         `db:"resource_type" json:"resource_type"`
	Amount       int64          `db:"amount" json:"amount"`
	Reason       sql.NullString `db:"reason" json:"reason"`
	TbTransferID []byte         `db:"tb_transfer_id" json:"tb_transfer_id"`
	CreatedAt    time.Time      `db:"created_at" json:"created_at"`
}

type QuotaConfig struct {
	TenantID           uuid.UUID     `db:"tenant_id" json:"tenant_id"`
	ResourceType       string        `db:"resource_type" json:"resource_type"`
	BasePlanID         uuid.NullUUID `db:"base_plan_id" json:"base_plan_id"`
	HardLimit          int64         `db:"hard_limit" json:"hard_limit"`
	SoftLimit          sql.NullInt64 `db:"soft_limit" json:"soft_limit"`
	BurstCredits       int64         `db:"burst_credits" json:"burst_credits"`
	BillingPeriod      string        `db:"billing_period" json:"billing_period"`
	SoftLimitAlertSent bool          `db:"soft_limit_alert_sent" json:"soft_limit_alert_sent"`
}

type QuotaSnapshot struct {
	TenantID      uuid.UUID     `db:"tenant_id" json:"tenant_id"`
	ResourceType  string        `db:"resource_type" json:"resource_type"`
	CreditsTotal  int64         `db:"credits_total" json:"credits_total"`
	DebitsPosted  int64         `db:"debits_posted" json:"debits_posted"`
	DebitsPending int64         `db:"debits_pending" json:"debits_pending"`
	Available     sql.NullInt64 `db:"available" json:"available"`
	SnapshotAt    time.Time     `db:"snapshot_at" json:"snapshot_at"`
}

type TbAccountID struct {
	TenantID     uuid.UUID `db:"tenant_id" json:"tenant_id"`
	ResourceType string    `db:"resource_type" json:"resource_type"`
	AccountType  string    `db:"account_type" json:"account_type"`
	TbAccountID  []byte    `db:"tb_account_id" json:"tb_account_id"`
	CreatedAt    time.Time `db:"created_at" json:"created_at"`
}

type TbGlobalAccountID struct {
	ResourceType string    `db:"resource_type" json:"resource_type"`
	AccountType  string    `db:"account_type" json:"account_type"`
	TbAccountID  []byte    `db:"tb_account_id" json:"tb_account_id"`
	CreatedAt    time.Time `db:"created_at" json:"created_at"`
}

type Tenant struct {
	ID          uuid.UUID    `db:"id" json:"id"`
	Name        string       `db:"name" json:"name"`
	BillingTier string       `db:"billing_tier" json:"billing_tier"`
	Status      string       `db:"status" json:"status"`
	CreatedAt   time.Time    `db:"created_at" json:"created_at"`
	DeletedAt   sql.NullTime `db:"deleted_at" json:"deleted_at"`
}

type WorkloadCluster struct {
	ID             uuid.UUID      `db:"id" json:"id"`
	TenantID       uuid.UUID      `db:"tenant_id" json:"tenant_id"`
	CloudProvider  string         `db:"cloud_provider" json:"cloud_provider"`
	Region         string         `db:"region" json:"region"`
	LastHeartbeat  sql.NullTime   `db:"last_heartbeat" json:"last_heartbeat"`
	Status         string         `db:"status" json:"status"`
	AgentVersion   sql.NullString `db:"agent_version" json:"agent_version"`
	DeregisteredAt sql.NullTime   `db:"deregistered_at" json:"deregistered_at"`
	CreatedAt      time.Time      `db:"created_at" json:"created_at"`
}
