// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: quota.sql

package sqlcgen

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const getAllQuotaSnapshots = `-- name: GetAllQuotaSnapshots :many
SELECT tenant_id, resource_type, credits_total, debits_posted, debits_pending, available, snapshot_at FROM quota_snapshots
ORDER BY tenant_id, resource_type
`

func (q *Queries) GetAllQuotaSnapshots(ctx context.Context) ([]QuotaSnapshot, error) {
	rows, err := q.db.QueryContext(ctx, getAllQuotaSnapshots)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QuotaSnapshot
	for rows.Next() {
		var i QuotaSnapshot
		if err := rows.Scan(
			&i.TenantID,
			&i.ResourceType,
			&i.CreditsTotal,
			&i.DebitsPosted,
			&i.DebitsPending,
			&i.Available,
			&i.SnapshotAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGlobalTBAccount = `-- name: GetGlobalTBAccount :one
SELECT tb_account_id FROM tb_global_account_ids
WHERE resource_type = $1 AND account_type = $2
`

func (q *Queries) GetGlobalTBAccount(ctx context.Context, resourceType string, accountType string) ([]byte, error) {
	row := q.db.QueryRowContext(ctx, getGlobalTBAccount, resourceType, accountType)
	var tb_account_id []byte
	err := row.Scan(&tb_account_id)
	return tb_account_id, err
}

const getGlobalTBAccounts = `-- name: GetGlobalTBAccounts :many
SELECT resource_type, account_type, tb_account_id, created_at FROM tb_global_account_ids
`

func (q *Queries) GetGlobalTBAccounts(ctx context.Context) ([]TbGlobalAccountID, error) {
	rows, err := q.db.QueryContext(ctx, getGlobalTBAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TbGlobalAccountID
	for rows.Next() {
		var i TbGlobalAccountID
		if err := rows.Scan(
			&i.ResourceType,
			&i.AccountType,
			&i.TbAccountID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getQuotaSnapshots = `-- name: GetQuotaSnapshots :many
SELECT tenant_id, resource_type, credits_total, debits_posted, debits_pending, available, snapshot_at FROM quota_snapshots WHERE tenant_id = $1
`

func (q *Queries) GetQuotaSnapshots(ctx context.Context, tenantID uuid.UUID) ([]QuotaSnapshot, error) {
	rows, err := q.db.QueryContext(ctx, getQuotaSnapshots, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QuotaSnapshot
	for rows.Next() {
		var i QuotaSnapshot
		if err := rows.Scan(
			&i.TenantID,
			&i.ResourceType,
			&i.CreditsTotal,
			&i.DebitsPosted,
			&i.DebitsPending,
			&i.Available,
			&i.SnapshotAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTBAccountIDs = `-- name: GetTBAccountIDs :many
SELECT tenant_id, resource_type, account_type, tb_account_id, created_at FROM tb_account_ids WHERE tenant_id = $1
`

func (q *Queries) GetTBAccountIDs(ctx context.Context, tenantID uuid.UUID) ([]TbAccountID, error) {
	rows, err := q.db.QueryContext(ctx, getTBAccountIDs, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TbAccountID
	for rows.Next() {
		var i TbAccountID
		if err := rows.Scan(
			&i.TenantID,
			&i.ResourceType,
			&i.AccountType,
			&i.TbAccountID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertCreditAdjustment = `-- name: InsertCreditAdjustment :exec
INSERT INTO credit_adjustments (tenant_id, resource_type, amount, reason, tb_transfer_id)
VALUES ($1, $2, $3, $4, $5)
`

func (q *Queries) InsertCreditAdjustment(ctx context.Context, tenantID uuid.UUID, resourceType string, amount int64, reason sql.NullString, tbTransferID []byte) error {
	_, err := q.db.ExecContext(ctx, insertCreditAdjustment,
		tenantID,
		resourceType,
		amount,
		reason,
		tbTransferID,
	)
	return err
}

const insertGlobalTBAccount = `-- name: InsertGlobalTBAccount :exec
INSERT INTO tb_global_account_ids (resource_type, account_type, tb_account_id)
VALUES ($1, $2, $3)
ON CONFLICT (resource_type, account_type) DO NOTHING
`

func (q *Queries) InsertGlobalTBAccount(ctx context.Context, resourceType string, accountType string, tbAccountID []byte) error {
	_, err := q.db.ExecContext(ctx, insertGlobalTBAccount, resourceType, accountType, tbAccountID)
	return err
}

const insertQuotaConfig = `-- name: InsertQuotaConfig :exec
INSERT INTO quota_configs (tenant_id, resource_type, hard_limit, soft_limit)
VALUES ($1, $2, $3, $4)
ON CONFLICT (tenant_id, resource_type) DO NOTHING
`

func (q *Queries) InsertQuotaConfig(ctx context.Context, tenantID uuid.UUID, resourceType string, hardLimit int64, softLimit sql.NullInt64) error {
	_, err := q.db.ExecContext(ctx, insertQuotaConfig,
		tenantID,
		resourceType,
		hardLimit,
		softLimit,
	)
	return err
}

const insertTBAccountMapping = `-- name: InsertTBAccountMapping :exec
INSERT INTO tb_account_ids (tenant_id, resource_type, account_type, tb_account_id)
VALUES ($1, $2, $3, $4)
ON CONFLICT (tenant_id, resource_type, account_type) DO NOTHING
`

func (q *Queries) InsertTBAccountMapping(ctx context.Context, tenantID uuid.UUID, resourceType string, accountType string, tbAccountID []byte) error {
	_, err := q.db.ExecContext(ctx, insertTBAccountMapping,
		tenantID,
		resourceType,
		accountType,
		tbAccountID,
	)
	return err
}

const listCreditAdjustmentsByTenant = `-- name: ListCreditAdjustmentsByTenant :many
SELECT id, tenant_id, resource_type, amount, reason, tb_transfer_id, created_at FROM credit_adjustments
WHERE tenant_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListCreditAdjustmentsByTenant(ctx context.Context, tenantID uuid.UUID) ([]CreditAdjustment, error) {
	rows, err := q.db.QueryContext(ctx, listCreditAdjustmentsByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CreditAdjustment
	for rows.Next() {
		var i CreditAdjustment
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ResourceType,
			&i.Amount,
			&i.Reason,
			&i.TbTransferID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQuotaConfigsByTenant = `-- name: ListQuotaConfigsByTenant :many
SELECT tenant_id, resource_type, base_plan_id, hard_limit, soft_limit, burst_credits, billing_period, soft_limit_alert_sent FROM quota_configs WHERE tenant_id = $1
`

func (q *Queries) ListQuotaConfigsByTenant(ctx context.Context, tenantID uuid.UUID) ([]QuotaConfig, error) {
	rows, err := q.db.QueryContext(ctx, listQuotaConfigsByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QuotaConfig
	for rows.Next() {
		var i QuotaConfig
		if err := rows.Scan(
			&i.TenantID,
			&i.ResourceType,
			&i.BasePlanID,
			&i.HardLimit,
			&i.SoftLimit,
			&i.BurstCredits,
			&i.BillingPeriod,
			&i.SoftLimitAlertSent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markSoftLimitAlertSent = `-- name: MarkSoftLimitAlertSent :exec
UPDATE quota_configs
SET soft_limit_alert_sent = TRUE
WHERE tenant_id = $1 AND resource_type = $2
`

func (q *Queries) MarkSoftLimitAlertSent(ctx context.Context, tenantID uuid.UUID, resourceType string) error {
	_, err := q.db.ExecContext(ctx, markSoftLimitAlertSent, tenantID, resourceType)
	return err
}

const resetSoftLimitAlert = `-- name: ResetSoftLimitAlert :exec
UPDATE quota_configs
SET soft_limit_alert_sent = FALSE
WHERE tenant_id = $1 AND resource_type = $2
`

func (q *Queries) ResetSoftLimitAlert(ctx context.Context, tenantID uuid.UUID, resourceType string) error {
	_, err := q.db.ExecContext(ctx, resetSoftLimitAlert, tenantID, resourceType)
	return err
}

const upsertQuotaSnapshot = `-- name: UpsertQuotaSnapshot :exec
INSERT INTO quota_snapshots (tenant_id, resource_type, credits_total, debits_posted, debits_pending, snapshot_at)
VALUES ($1, $2, $3, $4, $5, NOW())
ON CONFLICT (tenant_id, resource_type) DO UPDATE SET
  credits_total  = EXCLUDED.credits_total,
  debits_posted  = EXCLUDED.debits_posted,
  debits_pending = EXCLUDED.debits_pending,
  snapshot_at    = NOW()
`

func (q *Queries) UpsertQuotaSnapshot(ctx context.Context, tenantID uuid.UUID, resourceType string, creditsTotal int64, debitsPosted int64, debitsPending int64) error {
	_, err := q.db.ExecContext(ctx, upsertQuotaSnapshot,
		tenantID,
		resourceType,
		creditsTotal,
		debitsPosted,
		debitsPending,
	)
	return err
}
