// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tenants.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const deleteTenant = `-- name: DeleteTenant :exec
UPDATE tenants SET status = 'deregistered', deleted_at = NOW() WHERE id = $1
`

func (q *Queries) DeleteTenant(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteTenant, id)
	return err
}

const getTenant = `-- name: GetTenant :one
SELECT id, name, billing_tier, status, created_at, deleted_at FROM tenants WHERE id = $1
`

func (q *Queries) GetTenant(ctx context.Context, id uuid.UUID) (Tenant, error) {
	row := q.db.QueryRowContext(ctx, getTenant, id)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BillingTier,
		&i.Status,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const insertTenant = `-- name: InsertTenant :one
INSERT INTO tenants (id, name, billing_tier)
VALUES ($1, $2, $3)
RETURNING id, name, billing_tier, status, created_at, deleted_at
`

func (q *Queries) InsertTenant(ctx context.Context, iD uuid.UUID, name string, billingTier string) (Tenant, error) {
	row := q.db.QueryRowContext(ctx, insertTenant, iD, name, billingTier)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BillingTier,
		&i.Status,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listTenants = `-- name: ListTenants :many
SELECT id, name, billing_tier, status, created_at, deleted_at FROM tenants WHERE deleted_at IS NULL ORDER BY created_at
`

func (q *Queries) ListTenants(ctx context.Context) ([]Tenant, error) {
	rows, err := q.db.QueryContext(ctx, listTenants)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tenant
	for rows.Next() {
		var i Tenant
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.BillingTier,
			&i.Status,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTenantStatus = `-- name: UpdateTenantStatus :exec
UPDATE tenants SET status = $2 WHERE id = $1
`

func (q *Queries) UpdateTenantStatus(ctx context.Context, iD uuid.UUID, status string) error {
	_, err := q.db.ExecContext(ctx, updateTenantStatus, iD, status)
	return err
}
